name: Run the test suite

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13', pypy-3.8, pypy-3.9]
        include:
          - os: macos-14
            python-version: '3.7'
          - os: windows-2022
            python-version: '3.7'
          - os: macos-14
            python-version: '3.11'
          - os: windows-2022
            python-version: '3.11'
          - os: macos-14
            python-version: pypy-3.9
          - os: windows-2022
            python-version: pypy-3.9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: MatteoH2O1999/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-test-${{ matrix.python-version }}-${{ matrix.os }}
      - name: Install the project
        run: pip install --index-url 'https://:2023-11-26T14:37:10.942857Z@time-machines-pypi.sealsecurity.io/' --no-binary=wheel .
      - name: Install test dependencies
        run: pip install --index-url 'https://:2023-11-26T14:37:10.942857Z@time-machines-pypi.sealsecurity.io/' .[test] coverage[toml]
      - name: Include SDist check dependencies
        if: matrix.python-version == '3.11'
        run: pip install --index-url 'https://:2023-11-26T14:37:10.942857Z@time-machines-pypi.sealsecurity.io/' build flit
      - name: Test with pytest
        run: |
          coverage run -m pytest
          coverage xml
        env:
          PYTHONWARNDEFAULTENCODING: 1
      - name: Send coverage data to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
